import { Role } from '../../../core/models/role.model';

export const ROLE_MOCK: Role[] = [
  {
    id: 'r1a2b3c4-0001-0000-0000-000000000001',
    name: 'Administrador',
    code: 'admin',
    description: 'Acceso completo al sistema. Puede gestionar usuarios, roles y toda la configuración del sistema de trazabilidad.',
    permissions: [
      'usuarios.ver', 'usuarios.crear', 'usuarios.editar', 'usuarios.eliminar',
      'roles.ver', 'roles.crear', 'roles.editar', 'roles.eliminar',
      'catalogos.ver', 'catalogos.crear', 'catalogos.editar', 'catalogos.eliminar',
      'recepcion.ver', 'recepcion.crear', 'recepcion.editar', 'recepcion.eliminar',
      'corrales.ver', 'corrales.crear', 'corrales.editar', 'corrales.eliminar',
      'produccion.ver', 'produccion.crear', 'produccion.editar', 'produccion.eliminar',
      'despacho.ver', 'despacho.crear', 'despacho.editar', 'despacho.eliminar',
      'auditoria.ver', 'reportes.ver',
    ],
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'r1a2b3c4-0001-0000-0000-000000000002',
    name: 'Supervisor',
    code: 'supervisor',
    description: 'Supervisión de operaciones de recepción, corrales, producción y despacho. Puede ver y editar registros pero no eliminar ni gestionar usuarios.',
    permissions: [
      'catalogos.ver',
      'recepcion.ver', 'recepcion.crear', 'recepcion.editar',
      'corrales.ver', 'corrales.crear', 'corrales.editar',
      'produccion.ver', 'produccion.crear', 'produccion.editar',
      'despacho.ver', 'despacho.crear', 'despacho.editar',
      'auditoria.ver', 'reportes.ver',
    ],
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'r1a2b3c4-0001-0000-0000-000000000003',
    name: 'Operador',
    code: 'operador',
    description: 'Registro de operaciones en planta: recepción de animales, movimientos en corrales y datos de producción (faena). Acceso limitado a módulos operativos.',
    permissions: [
      'catalogos.ver',
      'recepcion.ver', 'recepcion.crear',
      'corrales.ver', 'corrales.crear', 'corrales.editar',
      'produccion.ver', 'produccion.crear',
    ],
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-08-20'),
  },
  {
    id: 'r1a2b3c4-0001-0000-0000-000000000004',
    name: 'Auditor',
    code: 'auditor',
    description: 'Acceso de solo lectura a todos los módulos del sistema. Puede consultar la trazabilidad completa, bitácora de cambios y exportar reportes para auditorías internas o externas.',
    permissions: [
      'catalogos.ver',
      'recepcion.ver',
      'corrales.ver',
      'produccion.ver',
      'despacho.ver',
      'auditoria.ver', 'reportes.ver',
    ],
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-07-10'),
  },
  {
    id: 'r1a2b3c4-0001-0000-0000-000000000005',
    name: 'Visualizador',
    code: 'visualizador',
    description: 'Acceso de consulta únicamente al dashboard y reportes básicos. No puede realizar ninguna acción de registro ni modificación.',
    permissions: [
      'reportes.ver',
    ],
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'r1a2b3c4-0001-0000-0000-000000000006',
    name: 'Operador de Despacho',
    code: 'operador_despacho',
    description: 'Rol especializado para el área de despacho y logística. Gestiona órdenes de salida, pesos finales y notas de entrega vinculadas al ganadero de origen.',
    permissions: [
      'catalogos.ver',
      'produccion.ver',
      'despacho.ver', 'despacho.crear', 'despacho.editar',
      'reportes.ver',
    ],
    isActive: false,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-05-30'),
  },
];
